-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 21:56:00 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema centre_formation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `centre_formation` ;

-- -----------------------------------------------------
-- Schema centre_formation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centre_formation` DEFAULT CHARACTER SET utf8 ;
USE `centre_formation` ;

-- -----------------------------------------------------
-- Table `centre_formation`.`promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centre_formation`.`promotion` ;

CREATE TABLE IF NOT EXISTS `centre_formation`.`promotion` (
  `id_promotion` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_promotion`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centre_formation`.`personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centre_formation`.`personne` ;

CREATE TABLE IF NOT EXISTS `centre_formation`.`personne` (
  `id_personne` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_personne`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `centre_formation`.``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centre_formation`.`membre_promotion` ;

CREATE TABLE IF NOT EXISTS `centre_formation`.`membre_promotion` (
  `id_promotion` BIGINT(20) NOT NULL,
  `id_personne` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_promotion`, `id_personne`),
  INDEX `fk_membre_promotion_personne` (`id_personne` ASC),
  INDEX `fk_membre_promotion_promotion` (`id_promotion` ASC),
  CONSTRAINT `fk_membre_promotion_promotion`
  FOREIGN KEY (`id_promotion`)
  REFERENCES `centre_formation`.`promotion` (`id_promotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membre_promotion_personne`
  FOREIGN KEY (`id_personne`)
  REFERENCES `centre_formation`.`personne` (`id_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `centre_formation`.`projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centre_formation`.`projet` ;

CREATE TABLE IF NOT EXISTS `centre_formation`.`projet` (
  `id_projet` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_promotion` BIGINT(20) NOT NULL,
  `id_createur` BIGINT(20) NOT NULL,
  `sujet` TEXT NOT NULL,
  `titre` VARCHAR(100) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_limite` DATETIME NOT NULL,
  PRIMARY KEY (`id_projet`),
  INDEX `fk_projet_promotion` (`id_promotion` ASC),
  INDEX `fk_projet_personne` (`id_createur` ASC),
  CONSTRAINT `fk_projet_promotion`
    FOREIGN KEY (`id_promotion`)
    REFERENCES `centre_formation`.`promotion` (`id_promotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_personne`
    FOREIGN KEY (`id_createur`)
    REFERENCES `centre_formation`.`personne` (`id_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centre_formation`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centre_formation`.`equipe` ;

CREATE TABLE IF NOT EXISTS `centre_formation`.`equipe` (
  `id_equipe` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_projet` BIGINT(20) NOT NULL,
  `id_createur` BIGINT(20) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `resume` VARCHAR(255) NULL,
  PRIMARY KEY (`id_equipe`),
  INDEX `fk_equipe_projet` (`id_projet` ASC),
  INDEX `fk_equipe_personne` (`id_createur` ASC),
  CONSTRAINT `fk_equipe_projet`
    FOREIGN KEY (`id_projet`)
    REFERENCES `centre_formation`.`projet` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_personne`
    FOREIGN KEY (`id_createur`)
    REFERENCES `centre_formation`.`personne` (`id_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centre_formation`.`membre_equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centre_formation`.`membre_equipe` ;

CREATE TABLE IF NOT EXISTS `centre_formation`.`membre_equipe` (
  `id_equipe` BIGINT(20) NOT NULL,
  `id_personne` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_equipe`, `id_personne`),
  INDEX `fk_membre_equipe_personne` (`id_personne` ASC),
  INDEX `fk_membre_equipe_equipe` (`id_equipe` ASC),
  CONSTRAINT `fk_membre_equipe_equipe`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `centre_formation`.`equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membre_equipe_personne`
    FOREIGN KEY (`id_personne`)
    REFERENCES `centre_formation`.`personne` (`id_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
